/**
 * Banco de preguntas para la oposición TAI
 * 20 preguntas por bloque + 20 preguntas generales
 */

import { Question, BlockType } from './types';

export const questionsBank: Question[] = [
  // ============ BLOQUE 1: Organización del Estado (20 preguntas) ============
  {
    id: 'b1_q1',
    block: 'block1',
    theme: 1,
    text: '¿Cuál es el órgano supremo de la representación del pueblo español?',
    options: {
      a: 'El Gobierno',
      b: 'Las Cortes Generales',
      c: 'El Tribunal Constitucional',
      d: 'El Defensor del Pueblo',
    },
    correctAnswer: 'b',
    explanation: 'Las Cortes Generales son el órgano supremo de representación del pueblo español según la Constitución de 1978.',
  },
  {
    id: 'b1_q2',
    block: 'block1',
    theme: 1,
    text: '¿Cuántas cámaras componen las Cortes Generales?',
    options: {
      a: 'Una',
      b: 'Dos',
      c: 'Tres',
      d: 'Cuatro',
    },
    correctAnswer: 'b',
    explanation: 'Las Cortes Generales están compuestas por el Congreso de los Diputados y el Senado.',
  },
  {
    id: 'b1_q3',
    block: 'block1',
    theme: 2,
    text: '¿Quién es el Jefe del Estado en España?',
    options: {
      a: 'El Presidente del Gobierno',
      b: 'El Rey',
      c: 'El Presidente del Congreso',
      d: 'El Presidente del Tribunal Constitucional',
    },
    correctAnswer: 'b',
    explanation: 'El Rey es el Jefe del Estado según la Constitución Española de 1978.',
  },
  {
    id: 'b1_q4',
    block: 'block1',
    theme: 3,
    text: '¿Cuál es la máxima autoridad ejecutiva en España?',
    options: {
      a: 'El Rey',
      b: 'El Presidente del Congreso',
      c: 'El Presidente del Gobierno',
      d: 'El Defensor del Pueblo',
    },
    correctAnswer: 'c',
    explanation: 'El Presidente del Gobierno es la máxima autoridad ejecutiva en España.',
  },
  {
    id: 'b1_q5',
    block: 'block1',
    theme: 3,
    text: '¿Cuántos ministros componen típicamente el Gobierno español?',
    options: {
      a: 'Entre 10 y 15',
      b: 'Entre 15 y 20',
      c: 'Entre 20 y 25',
      d: 'Más de 30',
    },
    correctAnswer: 'b',
    explanation: 'El Gobierno español está compuesto típicamente por entre 15 y 20 ministros, aunque puede variar según la legislatura.',
  },
  {
    id: 'b1_q6',
    block: 'block1',
    theme: 4,
    text: '¿Cuál es el principal derecho fundamental reconocido en la Constitución Española?',
    options: {
      a: 'El derecho al trabajo',
      b: 'El derecho a la vida',
      c: 'El derecho a la educación',
      d: 'El derecho a la propiedad privada',
    },
    correctAnswer: 'b',
    explanation: 'El derecho a la vida es uno de los derechos fundamentales más importantes reconocidos en la Constitución.',
  },
  {
    id: 'b1_q7',
    block: 'block1',
    theme: 4,
    text: '¿Qué es el Estatuto Básico del Empleado Público?',
    options: {
      a: 'Una ley que regula los derechos y deberes de los funcionarios públicos',
      b: 'Un reglamento interno de cada ministerio',
      c: 'Una norma que solo aplica a empleados locales',
      d: 'Un documento que establece salarios mínimos',
    },
    correctAnswer: 'a',
    explanation: 'El Estatuto Básico del Empleado Público es una ley que regula los derechos, deberes y régimen de los funcionarios públicos.',
  },
  {
    id: 'b1_q8',
    block: 'block1',
    theme: 5,
    text: '¿Cuál es el objetivo principal de la Ley de Igualdad de Género?',
    options: {
      a: 'Garantizar la igualdad de oportunidades entre hombres y mujeres',
      b: 'Establecer cuotas de empleo femenino',
      c: 'Prohibir el trabajo de las mujeres',
      d: 'Crear departamentos separados por género',
    },
    correctAnswer: 'a',
    explanation: 'La Ley de Igualdad tiene como objetivo garantizar la igualdad de oportunidades y trato entre hombres y mujeres.',
  },
  {
    id: 'b1_q9',
    block: 'block1',
    theme: 6,
    text: '¿Qué es el DNI electrónico?',
    options: {
      a: 'Un documento de identidad digital sin valor legal',
      b: 'Un documento de identidad que incluye certificados digitales para autenticación',
      c: 'Un carnet de biblioteca',
      d: 'Un permiso de conducir electrónico',
    },
    correctAnswer: 'b',
    explanation: 'El DNI electrónico es un documento de identidad que incluye certificados digitales para autenticación e identificación en trámites electrónicos.',
  },
  {
    id: 'b1_q10',
    block: 'block1',
    theme: 7,
    text: '¿Cuál es el principal objetivo del Reglamento General de Protección de Datos (RGPD)?',
    options: {
      a: 'Aumentar la recopilación de datos personales',
      b: 'Proteger los derechos y libertades de las personas respecto al tratamiento de datos',
      c: 'Facilitar el acceso de empresas a datos personales',
      d: 'Eliminar todos los datos personales de internet',
    },
    correctAnswer: 'b',
    explanation: 'El RGPD tiene como objetivo proteger los derechos y libertades de las personas físicas respecto al tratamiento de datos personales.',
  },
  {
    id: 'b1_q11',
    block: 'block1',
    theme: 7,
    text: '¿Qué es el derecho al olvido en protección de datos?',
    options: {
      a: 'El derecho a no recordar información personal',
      b: 'El derecho a solicitar la eliminación de datos personales',
      c: 'El derecho a mentir sobre datos personales',
      d: 'El derecho a no compartir datos con nadie',
    },
    correctAnswer: 'b',
    explanation: 'El derecho al olvido es el derecho a solicitar la eliminación de datos personales cuando ya no sean necesarios o se retire el consentimiento.',
  },
  {
    id: 'b1_q12',
    block: 'block1',
    theme: 8,
    text: '¿Qué es la administración electrónica?',
    options: {
      a: 'El uso exclusivo de correo electrónico en administración',
      b: 'La prestación de servicios públicos mediante medios electrónicos',
      c: 'Un sistema para enviar facturas por email',
      d: 'Un programa de contabilidad para empresas',
    },
    correctAnswer: 'b',
    explanation: 'La administración electrónica es la prestación de servicios públicos mediante medios electrónicos, permitiendo trámites online.',
  },
  {
    id: 'b1_q13',
    block: 'block1',
    theme: 8,
    text: '¿Qué es el Esquema Nacional de Seguridad (ENS)?',
    options: {
      a: 'Un sistema de vigilancia de ciudadanos',
      b: 'Un conjunto de medidas de seguridad para sistemas de información de la administración',
      c: 'Un programa de defensa nacional',
      d: 'Un protocolo de comunicación de internet',
    },
    correctAnswer: 'b',
    explanation: 'El ENS es un conjunto de medidas de seguridad que establece los requisitos mínimos para proteger sistemas de información de la administración.',
  },
  {
    id: 'b1_q14',
    block: 'block1',
    theme: 8,
    text: '¿Qué es una sede electrónica?',
    options: {
      a: 'Una oficina física con computadoras',
      b: 'Un sitio web donde se prestan servicios públicos de forma electrónica',
      c: 'Una dirección de correo electrónico',
      d: 'Un servidor de internet',
    },
    correctAnswer: 'b',
    explanation: 'Una sede electrónica es un sitio web desde el cual se prestan servicios públicos de forma electrónica y se realizan trámites administrativos.',
  },
  {
    id: 'b1_q15',
    block: 'block1',
    theme: 9,
    text: '¿Cuál es el principal objetivo del Tribunal Constitucional?',
    options: {
      a: 'Juzgar delitos graves',
      b: 'Garantizar la supremacía de la Constitución',
      c: 'Administrar justicia civil',
      d: 'Controlar el comercio internacional',
    },
    correctAnswer: 'b',
    explanation: 'El Tribunal Constitucional tiene como objetivo garantizar la supremacía de la Constitución y resolver conflictos de competencias.',
  },
  {
    id: 'b1_q16',
    block: 'block1',
    theme: 1,
    text: '¿Cuántos artículos tiene la Constitución Española de 1978?',
    options: {
      a: '169',
      b: '178',
      c: '195',
      d: '210',
    },
    correctAnswer: 'b',
    explanation: 'La Constitución Española de 1978 tiene 178 artículos más disposiciones transitorias, adicionales y finales.',
  },
  {
    id: 'b1_q17',
    block: 'block1',
    theme: 2,
    text: '¿Cuál es el período de mandato del Rey de España?',
    options: {
      a: '4 años',
      b: '6 años',
      c: 'De por vida',
      d: '8 años',
    },
    correctAnswer: 'c',
    explanation: 'El Rey de España tiene un mandato de por vida, siendo una monarquía constitucional hereditaria.',
  },
  {
    id: 'b1_q18',
    block: 'block1',
    theme: 3,
    text: '¿Cuántos diputados componen el Congreso de los Diputados?',
    options: {
      a: '300',
      b: '350',
      c: '400',
      d: '450',
    },
    correctAnswer: 'b',
    explanation: 'El Congreso de los Diputados está compuesto por 350 diputados elegidos por sufragio universal directo.',
  },
  {
    id: 'b1_q19',
    block: 'block1',
    theme: 4,
    text: '¿Qué es la Agenda 2030?',
    options: {
      a: 'Un plan de eventos del Gobierno español',
      b: 'Un programa de Naciones Unidas con objetivos de desarrollo sostenible',
      c: 'Un calendario de reuniones internacionales',
      d: 'Un plan de reforma administrativa',
    },
    correctAnswer: 'b',
    explanation: 'La Agenda 2030 es un programa de Naciones Unidas que establece 17 Objetivos de Desarrollo Sostenible.',
  },
  {
    id: 'b1_q20',
    block: 'block1',
    theme: 5,
    text: '¿Cuál es el rol del Defensor del Pueblo?',
    options: {
      a: 'Defender al pueblo en juicios civiles',
      b: 'Supervisar la actividad de la administración pública y proteger derechos',
      c: 'Dirigir el Gobierno',
      d: 'Controlar el Tribunal Constitucional',
    },
    correctAnswer: 'b',
    explanation: 'El Defensor del Pueblo es un órgano constitucional que supervisa la actividad de la administración pública y protege los derechos de los ciudadanos.',
  },

  // ============ BLOQUE 2: Tecnología Básica (20 preguntas) ============
  {
    id: 'b2_q1',
    block: 'block2',
    theme: 1,
    text: '¿Cuál es la unidad básica de información en un sistema informático?',
    options: {
      a: 'Byte',
      b: 'Bit',
      c: 'Kilobyte',
      d: 'Megabyte',
    },
    correctAnswer: 'b',
    explanation: 'El bit (binary digit) es la unidad básica de información, representando 0 o 1.',
  },
  {
    id: 'b2_q2',
    block: 'block2',
    theme: 1,
    text: '¿Cuántos bits componen un byte?',
    options: {
      a: '4',
      b: '8',
      c: '16',
      d: '32',
    },
    correctAnswer: 'b',
    explanation: 'Un byte está compuesto por 8 bits.',
  },
  {
    id: 'b2_q3',
    block: 'block2',
    theme: 1,
    text: '¿Cuál es la función principal de la CPU (Unidad Central de Procesamiento)?',
    options: {
      a: 'Almacenar datos permanentemente',
      b: 'Ejecutar instrucciones y realizar cálculos',
      c: 'Conectarse a internet',
      d: 'Mostrar imágenes en pantalla',
    },
    correctAnswer: 'b',
    explanation: 'La CPU ejecuta las instrucciones del programa y realiza los cálculos necesarios.',
  },
  {
    id: 'b2_q4',
    block: 'block2',
    theme: 1,
    text: '¿Qué es la RAM?',
    options: {
      a: 'Memoria de acceso permanente',
      b: 'Memoria de acceso aleatorio temporal',
      c: 'Memoria de solo lectura',
      d: 'Memoria de almacenamiento externo',
    },
    correctAnswer: 'b',
    explanation: 'RAM (Random Access Memory) es una memoria temporal de acceso rápido que se borra al apagar el equipo.',
  },
  {
    id: 'b2_q5',
    block: 'block2',
    theme: 2,
    text: '¿Cuál es la función principal de un disco duro?',
    options: {
      a: 'Procesar datos',
      b: 'Almacenar datos permanentemente',
      c: 'Mostrar imágenes',
      d: 'Amplificar señales de audio',
    },
    correctAnswer: 'b',
    explanation: 'El disco duro es el dispositivo de almacenamiento permanente de datos en un ordenador.',
  },
  {
    id: 'b2_q6',
    block: 'block2',
    theme: 2,
    text: '¿Qué es un SSD?',
    options: {
      a: 'Un tipo de monitor',
      b: 'Un dispositivo de almacenamiento de estado sólido sin partes móviles',
      c: 'Un tipo de procesador',
      d: 'Un periférico de entrada',
    },
    correctAnswer: 'b',
    explanation: 'SSD (Solid State Drive) es un dispositivo de almacenamiento sin partes móviles, más rápido que los discos duros tradicionales.',
  },
  {
    id: 'b2_q7',
    block: 'block2',
    theme: 3,
    text: '¿Cuál es el sistema de numeración utilizado internamente por los ordenadores?',
    options: {
      a: 'Decimal',
      b: 'Octal',
      c: 'Binario',
      d: 'Hexadecimal',
    },
    correctAnswer: 'c',
    explanation: 'Los ordenadores utilizan el sistema binario (0 y 1) internamente para representar toda la información.',
  },
  {
    id: 'b2_q8',
    block: 'block2',
    theme: 3,
    text: '¿Cuántos valores diferentes puede representar un bit?',
    options: {
      a: '1',
      b: '2',
      c: '4',
      d: '8',
    },
    correctAnswer: 'b',
    explanation: 'Un bit puede representar 2 valores: 0 o 1.',
  },
  {
    id: 'b2_q9',
    block: 'block2',
    theme: 4,
    text: '¿Cuál es la función principal de un sistema operativo?',
    options: {
      a: 'Crear documentos de texto',
      b: 'Gestionar los recursos del ordenador y proporcionar una interfaz al usuario',
      c: 'Navegar por internet',
      d: 'Reproducir música',
    },
    correctAnswer: 'b',
    explanation: 'El sistema operativo gestiona los recursos del ordenador y proporciona una interfaz para que el usuario interactúe con el equipo.',
  },
  {
    id: 'b2_q10',
    block: 'block2',
    theme: 4,
    text: '¿Cuál es el sistema operativo más utilizado en servidores?',
    options: {
      a: 'Windows',
      b: 'macOS',
      c: 'Linux',
      d: 'iOS',
    },
    correctAnswer: 'c',
    explanation: 'Linux es el sistema operativo más utilizado en servidores debido a su estabilidad y flexibilidad.',
  },
  {
    id: 'b2_q11',
    block: 'block2',
    theme: 4,
    text: '¿Qué es Windows?',
    options: {
      a: 'Un navegador web',
      b: 'Un sistema operativo desarrollado por Microsoft',
      c: 'Un programa de edición de imágenes',
      d: 'Un lenguaje de programación',
    },
    correctAnswer: 'b',
    explanation: 'Windows es un sistema operativo desarrollado por Microsoft para ordenadores personales.',
  },
  {
    id: 'b2_q12',
    block: 'block2',
    theme: 4,
    text: '¿Cuál es el sistema operativo de los dispositivos iPhone?',
    options: {
      a: 'Android',
      b: 'Windows',
      c: 'iOS',
      d: 'Linux',
    },
    correctAnswer: 'c',
    explanation: 'iOS es el sistema operativo desarrollado por Apple para los dispositivos iPhone.',
  },
  {
    id: 'b2_q13',
    block: 'block2',
    theme: 5,
    text: '¿Qué es una base de datos?',
    options: {
      a: 'Un programa para editar documentos',
      b: 'Un conjunto organizado de datos almacenados y accesibles',
      c: 'Un tipo de virus informático',
      d: 'Un navegador web',
    },
    correctAnswer: 'b',
    explanation: 'Una base de datos es un conjunto organizado de datos que se almacenan y se pueden acceder de forma estructurada.',
  },
  {
    id: 'b2_q14',
    block: 'block2',
    theme: 5,
    text: '¿Qué es SQL?',
    options: {
      a: 'Un lenguaje de programación para aplicaciones web',
      b: 'Un lenguaje de consulta para bases de datos',
      c: 'Un sistema operativo',
      d: 'Un tipo de archivo',
    },
    correctAnswer: 'b',
    explanation: 'SQL (Structured Query Language) es un lenguaje estándar para consultar y manipular bases de datos.',
  },
  {
    id: 'b2_q15',
    block: 'block2',
    theme: 5,
    text: '¿Cuál es el modelo de base de datos más utilizado?',
    options: {
      a: 'Jerárquico',
      b: 'En red',
      c: 'Relacional',
      d: 'Orientado a objetos',
    },
    correctAnswer: 'c',
    explanation: 'El modelo relacional es el más utilizado en bases de datos modernas.',
  },
  {
    id: 'b2_q16',
    block: 'block2',
    theme: 1,
    text: '¿Qué es la memoria caché?',
    options: {
      a: 'Un tipo de virus',
      b: 'Memoria rápida que almacena datos de acceso frecuente',
      c: 'Un programa antivirus',
      d: 'Un archivo temporal de internet',
    },
    correctAnswer: 'b',
    explanation: 'La memoria caché es una memoria rápida que almacena datos de acceso frecuente para mejorar el rendimiento.',
  },
  {
    id: 'b2_q17',
    block: 'block2',
    theme: 2,
    text: '¿Cuál es la velocidad típica de un puerto USB 3.0?',
    options: {
      a: '12 Mbps',
      b: '480 Mbps',
      c: '5 Gbps',
      d: '10 Gbps',
    },
    correctAnswer: 'c',
    explanation: 'USB 3.0 tiene una velocidad de transferencia de hasta 5 Gbps (gigabits por segundo).',
  },
  {
    id: 'b2_q18',
    block: 'block2',
    theme: 3,
    text: '¿Qué es el sistema hexadecimal?',
    options: {
      a: 'Un sistema de numeración con base 2',
      b: 'Un sistema de numeración con base 16',
      c: 'Un sistema de numeración con base 8',
      d: 'Un sistema de numeración con base 10',
    },
    correctAnswer: 'b',
    explanation: 'El sistema hexadecimal utiliza 16 dígitos (0-9 y A-F) y es ampliamente usado en informática.',
  },
  {
    id: 'b2_q19',
    block: 'block2',
    theme: 4,
    text: '¿Qué es un controlador (driver)?',
    options: {
      a: 'Un programa para conducir vehículos',
      b: 'Un software que permite que el sistema operativo controle un dispositivo hardware',
      c: 'Un tipo de archivo ejecutable',
      d: 'Un navegador web',
    },
    correctAnswer: 'b',
    explanation: 'Un controlador (driver) es un software que permite que el sistema operativo comunique y controle dispositivos hardware.',
  },
  {
    id: 'b2_q20',
    block: 'block2',
    theme: 5,
    text: '¿Qué es NoSQL?',
    options: {
      a: 'Una versión antigua de SQL',
      b: 'Un tipo de base de datos no relacional',
      c: 'Un lenguaje de programación',
      d: 'Un sistema operativo',
    },
    correctAnswer: 'b',
    explanation: 'NoSQL es un tipo de base de datos no relacional que permite almacenar datos de forma flexible.',
  },

  // ============ BLOQUE 3: Desarrollo de Sistemas (20 preguntas) ============
  {
    id: 'b3_q1',
    block: 'block3',
    theme: 1,
    text: '¿Qué es el modelado de datos?',
    options: {
      a: 'Un proceso de diseño de modelos de ropa',
      b: 'Un proceso de representación abstracta de datos y sus relaciones',
      c: 'Un tipo de fotografía',
      d: 'Un programa de edición de imágenes',
    },
    correctAnswer: 'b',
    explanation: 'El modelado de datos es un proceso de representación abstracta de los datos y sus relaciones en un sistema.',
  },
  {
    id: 'b3_q2',
    block: 'block3',
    theme: 1,
    text: '¿Qué es una entidad en el modelado de datos?',
    options: {
      a: 'Un tipo de virus',
      b: 'Un objeto del mundo real que queremos representar',
      c: 'Un archivo de datos',
      d: 'Un programa de base de datos',
    },
    correctAnswer: 'b',
    explanation: 'Una entidad es un objeto del mundo real (como una persona, producto, etc.) que queremos representar en el modelo de datos.',
  },
  {
    id: 'b3_q3',
    block: 'block3',
    theme: 2,
    text: '¿Cuál es el lenguaje de programación más utilizado actualmente?',
    options: {
      a: 'COBOL',
      b: 'Python',
      c: 'BASIC',
      d: 'FORTRAN',
    },
    correctAnswer: 'b',
    explanation: 'Python es uno de los lenguajes de programación más populares actualmente por su versatilidad y facilidad de aprendizaje.',
  },
  {
    id: 'b3_q4',
    block: 'block3',
    theme: 2,
    text: '¿Qué es Java?',
    options: {
      a: 'Un tipo de café',
      b: 'Un lenguaje de programación orientado a objetos',
      c: 'Un sistema operativo',
      d: 'Un navegador web',
    },
    correctAnswer: 'b',
    explanation: 'Java es un lenguaje de programación orientado a objetos, multiplataforma y ampliamente utilizado en empresas.',
  },
  {
    id: 'b3_q5',
    block: 'block3',
    theme: 2,
    text: '¿Cuál es la principal característica de la Programación Orientada a Objetos (POO)?',
    options: {
      a: 'Usar solo variables globales',
      b: 'Organizar el código en objetos con propiedades y métodos',
      c: 'Evitar el uso de funciones',
      d: 'Programar solo en lenguaje ensamblador',
    },
    correctAnswer: 'b',
    explanation: 'La POO organiza el código en objetos que contienen datos (propiedades) y funcionalidad (métodos).',
  },
  {
    id: 'b3_q6',
    block: 'block3',
    theme: 3,
    text: '¿Qué es SQL?',
    options: {
      a: 'Un lenguaje de programación general',
      b: 'Un lenguaje para consultar y manipular bases de datos',
      c: 'Un sistema operativo',
      d: 'Un tipo de archivo comprimido',
    },
    correctAnswer: 'b',
    explanation: 'SQL es un lenguaje estándar para consultar, insertar, actualizar y eliminar datos en bases de datos.',
  },
  {
    id: 'b3_q7',
    block: 'block3',
    theme: 3,
    text: '¿Cuál es la sentencia SQL más básica para recuperar datos?',
    options: {
      a: 'INSERT',
      b: 'UPDATE',
      c: 'SELECT',
      d: 'DELETE',
    },
    correctAnswer: 'c',
    explanation: 'SELECT es la sentencia SQL utilizada para recuperar datos de una base de datos.',
  },
  {
    id: 'b3_q8',
    block: 'block3',
    theme: 4,
    text: '¿Qué es una clase en programación orientada a objetos?',
    options: {
      a: 'Un tipo de archivo',
      b: 'Un plantilla o molde para crear objetos',
      c: 'Un programa ejecutable',
      d: 'Un tipo de virus',
    },
    correctAnswer: 'b',
    explanation: 'Una clase es una plantilla o molde que define la estructura y comportamiento de los objetos.',
  },
  {
    id: 'b3_q9',
    block: 'block3',
    theme: 4,
    text: '¿Qué es la herencia en POO?',
    options: {
      a: 'Recibir dinero de un familiar',
      b: 'Un mecanismo para que una clase herede propiedades y métodos de otra',
      c: 'Un tipo de archivo',
      d: 'Un programa de contabilidad',
    },
    correctAnswer: 'b',
    explanation: 'La herencia permite que una clase (subclase) herede propiedades y métodos de otra clase (superclase).',
  },
  {
    id: 'b3_q10',
    block: 'block3',
    theme: 4,
    text: '¿Qué es el polimorfismo en POO?',
    options: {
      a: 'Un tipo de virus',
      b: 'La capacidad de un objeto de tomar múltiples formas',
      c: 'Un lenguaje de programación',
      d: 'Un sistema operativo',
    },
    correctAnswer: 'b',
    explanation: 'El polimorfismo permite que objetos de diferentes clases respondan al mismo mensaje de diferentes formas.',
  },
  {
    id: 'b3_q11',
    block: 'block3',
    theme: 5,
    text: '¿Qué es una arquitectura cliente-servidor?',
    options: {
      a: 'Un tipo de computadora',
      b: 'Un modelo donde un cliente solicita servicios a un servidor',
      c: 'Un programa de diseño gráfico',
      d: 'Un tipo de archivo',
    },
    correctAnswer: 'b',
    explanation: 'La arquitectura cliente-servidor es un modelo donde los clientes solicitan recursos a un servidor central.',
  },
  {
    id: 'b3_q12',
    block: 'block3',
    theme: 5,
    text: '¿Qué es una arquitectura multicapas?',
    options: {
      a: 'Un tipo de pastel',
      b: 'Una arquitectura que divide la aplicación en capas independientes',
      c: 'Un programa de edición de imágenes',
      d: 'Un tipo de red',
    },
    correctAnswer: 'b',
    explanation: 'Una arquitectura multicapas divide la aplicación en capas (presentación, lógica, datos) independientes.',
  },
  {
    id: 'b3_q13',
    block: 'block3',
    theme: 6,
    text: '¿Qué es una aplicación web?',
    options: {
      a: 'Un programa que solo funciona en teléfonos',
      b: 'Un programa que se ejecuta en un navegador web',
      c: 'Un tipo de virus',
      d: 'Un archivo de datos',
    },
    correctAnswer: 'b',
    explanation: 'Una aplicación web es un programa que se ejecuta en un navegador web y accede a recursos a través de internet.',
  },
  {
    id: 'b3_q14',
    block: 'block3',
    theme: 6,
    text: '¿Cuál es el lenguaje principal para crear páginas web?',
    options: {
      a: 'Python',
      b: 'Java',
      c: 'HTML',
      d: 'C++',
    },
    correctAnswer: 'c',
    explanation: 'HTML es el lenguaje de marcado utilizado para crear la estructura de las páginas web.',
  },
  {
    id: 'b3_q15',
    block: 'block3',
    theme: 6,
    text: '¿Qué es CSS?',
    options: {
      a: 'Un lenguaje de programación',
      b: 'Un lenguaje para definir estilos en páginas web',
      c: 'Un sistema operativo',
      d: 'Un tipo de archivo comprimido',
    },
    correctAnswer: 'b',
    explanation: 'CSS (Cascading Style Sheets) es un lenguaje para definir estilos y diseño en páginas web.',
  },
  {
    id: 'b3_q16',
    block: 'block3',
    theme: 7,
    text: '¿Qué es la accesibilidad web?',
    options: {
      a: 'La velocidad de carga de un sitio web',
      b: 'El diseño de sitios web para que sean usables por todos, incluyendo personas con discapacidades',
      c: 'Un tipo de navegador web',
      d: 'Un programa antivirus',
    },
    correctAnswer: 'b',
    explanation: 'La accesibilidad web es el diseño de sitios web para que sean usables por todas las personas, incluyendo personas con discapacidades.',
  },
  {
    id: 'b3_q17',
    block: 'block3',
    theme: 8,
    text: '¿Qué es un repositorio de código?',
    options: {
      a: 'Un almacén de datos',
      b: 'Un sistema para almacenar y versionar código fuente',
      c: 'Un tipo de base de datos',
      d: 'Un programa de diseño',
    },
    correctAnswer: 'b',
    explanation: 'Un repositorio de código es un sistema (como Git) para almacenar, versionar y colaborar en código fuente.',
  },
  {
    id: 'b3_q18',
    block: 'block3',
    theme: 8,
    text: '¿Qué es Git?',
    options: {
      a: 'Un lenguaje de programación',
      b: 'Un sistema de control de versiones',
      c: 'Un navegador web',
      d: 'Un sistema operativo',
    },
    correctAnswer: 'b',
    explanation: 'Git es un sistema de control de versiones distribuido ampliamente utilizado para gestionar código fuente.',
  },
  {
    id: 'b3_q19',
    block: 'block3',
    theme: 9,
    text: '¿Qué es una prueba unitaria?',
    options: {
      a: 'Una prueba de velocidad de internet',
      b: 'Una prueba que verifica el funcionamiento de una unidad pequeña de código',
      c: 'Un tipo de virus',
      d: 'Un programa de diseño',
    },
    correctAnswer: 'b',
    explanation: 'Una prueba unitaria es una prueba que verifica el funcionamiento correcto de una pequeña unidad de código (función, método).',
  },
  {
    id: 'b3_q20',
    block: 'block3',
    theme: 10,
    text: '¿Qué es la metodología Agile?',
    options: {
      a: 'Un tipo de virus',
      b: 'Una metodología de desarrollo de software iterativa y flexible',
      c: 'Un lenguaje de programación',
      d: 'Un sistema operativo',
    },
    correctAnswer: 'b',
    explanation: 'Agile es una metodología de desarrollo de software que enfatiza la iteración, flexibilidad y colaboración.',
  },

  // ============ BLOQUE 4: Sistemas y Comunicaciones (20 preguntas) ============
  {
    id: 'b4_q1',
    block: 'block4',
    theme: 1,
    text: '¿Qué es una red de computadoras?',
    options: {
      a: 'Un conjunto de computadoras conectadas entre sí',
      b: 'Un programa de antivirus',
      c: 'Un tipo de archivo',
      d: 'Un navegador web',
    },
    correctAnswer: 'a',
    explanation: 'Una red de computadoras es un conjunto de computadoras conectadas entre sí para compartir recursos e información.',
  },
  {
    id: 'b4_q2',
    block: 'block4',
    theme: 1,
    text: '¿Qué es una LAN?',
    options: {
      a: 'Una red de área amplia',
      b: 'Una red de área local',
      c: 'Un tipo de archivo',
      d: 'Un programa de comunicación',
    },
    correctAnswer: 'b',
    explanation: 'LAN (Local Area Network) es una red de área local que conecta computadoras en una zona geográfica pequeña.',
  },
  {
    id: 'b4_q3',
    block: 'block4',
    theme: 1,
    text: '¿Qué es una WAN?',
    options: {
      a: 'Una red de área local',
      b: 'Una red de área amplia',
      c: 'Un tipo de archivo',
      d: 'Un programa de diseño',
    },
    correctAnswer: 'b',
    explanation: 'WAN (Wide Area Network) es una red de área amplia que conecta computadoras en zonas geográficas lejanas.',
  },
  {
    id: 'b4_q4',
    block: 'block4',
    theme: 2,
    text: '¿Qué es TCP/IP?',
    options: {
      a: 'Un tipo de virus',
      b: 'Un conjunto de protocolos de comunicación en redes',
      c: 'Un programa de diseño',
      d: 'Un sistema operativo',
    },
    correctAnswer: 'b',
    explanation: 'TCP/IP es un conjunto de protocolos de comunicación que forma la base de internet.',
  },
  {
    id: 'b4_q5',
    block: 'block4',
    theme: 2,
    text: '¿Cuál es la función del protocolo TCP?',
    options: {
      a: 'Transmitir datos sin garantía de entrega',
      b: 'Garantizar la entrega ordenada y confiable de datos',
      c: 'Resolver direcciones de dominio',
      d: 'Enviar correos electrónicos',
    },
    correctAnswer: 'b',
    explanation: 'TCP (Transmission Control Protocol) garantiza la entrega ordenada y confiable de datos entre computadoras.',
  },
  {
    id: 'b4_q6',
    block: 'block4',
    theme: 2,
    text: '¿Cuál es la función del protocolo IP?',
    options: {
      a: 'Garantizar la entrega de datos',
      b: 'Enrutar datos entre redes',
      c: 'Resolver nombres de dominio',
      d: 'Enviar correos electrónicos',
    },
    correctAnswer: 'b',
    explanation: 'IP (Internet Protocol) es responsable de enrutar datos entre redes usando direcciones IP.',
  },
  {
    id: 'b4_q7',
    block: 'block4',
    theme: 3,
    text: '¿Qué es una dirección IP?',
    options: {
      a: 'Un identificador único de una computadora en una red',
      b: 'Un tipo de archivo',
      c: 'Un programa de comunicación',
      d: 'Un navegador web',
    },
    correctAnswer: 'a',
    explanation: 'Una dirección IP es un identificador único que se asigna a cada dispositivo en una red para comunicarse.',
  },
  {
    id: 'b4_q8',
    block: 'block4',
    theme: 3,
    text: '¿Cuántos octetos tiene una dirección IPv4?',
    options: {
      a: '2',
      b: '4',
      c: '6',
      d: '8',
    },
    correctAnswer: 'b',
    explanation: 'Una dirección IPv4 tiene 4 octetos (grupos de números separados por puntos, ej: 192.168.1.1).',
  },
  {
    id: 'b4_q9',
    block: 'block4',
    theme: 4,
    text: '¿Qué es el protocolo HTTP?',
    options: {
      a: 'Un protocolo de transferencia de archivos',
      b: 'Un protocolo para transferir páginas web',
      c: 'Un protocolo de correo electrónico',
      d: 'Un protocolo de telefonía',
    },
    correctAnswer: 'b',
    explanation: 'HTTP (HyperText Transfer Protocol) es el protocolo utilizado para transferir páginas web en internet.',
  },
  {
    id: 'b4_q10',
    block: 'block4',
    theme: 4,
    text: '¿Qué es HTTPS?',
    options: {
      a: 'Una versión antigua de HTTP',
      b: 'HTTP con cifrado de seguridad',
      c: 'Un tipo de archivo',
      d: 'Un programa de diseño',
    },
    correctAnswer: 'b',
    explanation: 'HTTPS es HTTP con cifrado SSL/TLS para proteger la comunicación entre cliente y servidor.',
  },
  {
    id: 'b4_q11',
    block: 'block4',
    theme: 5,
    text: '¿Qué es un firewall?',
    options: {
      a: 'Un tipo de virus',
      b: 'Un software o hardware que controla el tráfico de red',
      c: 'Un programa de diseño',
      d: 'Un navegador web',
    },
    correctAnswer: 'b',
    explanation: 'Un firewall es un sistema de seguridad que controla el tráfico de red entre redes o computadoras.',
  },
  {
    id: 'b4_q12',
    block: 'block4',
    theme: 5,
    text: '¿Qué es una VPN?',
    options: {
      a: 'Un tipo de archivo',
      b: 'Una red privada virtual que cifra la comunicación',
      c: 'Un programa de diseño',
      d: 'Un navegador web',
    },
    correctAnswer: 'b',
    explanation: 'VPN (Virtual Private Network) es una red privada virtual que cifra la comunicación para mayor seguridad.',
  },
  {
    id: 'b4_q13',
    block: 'block4',
    theme: 5,
    text: '¿Qué es la criptografía?',
    options: {
      a: 'Un tipo de virus',
      b: 'La ciencia de cifrar y descifrar información',
      c: 'Un programa de diseño',
      d: 'Un tipo de archivo',
    },
    correctAnswer: 'b',
    explanation: 'La criptografía es la ciencia de cifrar información para protegerla de acceso no autorizado.',
  },
  {
    id: 'b4_q14',
    block: 'block4',
    theme: 5,
    text: '¿Qué es una firma digital?',
    options: {
      a: 'Una imagen de una firma escrita',
      b: 'Un mecanismo criptográfico para autenticar documentos',
      c: 'Un tipo de archivo',
      d: 'Un programa de diseño',
    },
    correctAnswer: 'b',
    explanation: 'Una firma digital es un mecanismo criptográfico que autentica la identidad del remitente de un documento.',
  },
  {
    id: 'b4_q15',
    block: 'block4',
    theme: 6,
    text: '¿Qué es un router?',
    options: {
      a: 'Un tipo de computadora',
      b: 'Un dispositivo que enruta datos entre redes',
      c: 'Un programa de diseño',
      d: 'Un navegador web',
    },
    correctAnswer: 'b',
    explanation: 'Un router es un dispositivo que enruta datos entre diferentes redes.',
  },
  {
    id: 'b4_q16',
    block: 'block4',
    theme: 6,
    text: '¿Qué es un switch?',
    options: {
      a: 'Un dispositivo para apagar/encender',
      b: 'Un dispositivo que conecta computadoras en una LAN',
      c: 'Un programa de diseño',
      d: 'Un tipo de archivo',
    },
    correctAnswer: 'b',
    explanation: 'Un switch es un dispositivo de red que conecta computadoras en una red local (LAN).',
  },
  {
    id: 'b4_q17',
    block: 'block4',
    theme: 7,
    text: '¿Qué es DNS?',
    options: {
      a: 'Un tipo de virus',
      b: 'Un sistema que traduce nombres de dominio a direcciones IP',
      c: 'Un programa de diseño',
      d: 'Un navegador web',
    },
    correctAnswer: 'b',
    explanation: 'DNS (Domain Name System) es un sistema que traduce nombres de dominio (como google.com) a direcciones IP.',
  },
  {
    id: 'b4_q18',
    block: 'block4',
    theme: 8,
    text: '¿Qué es un servidor?',
    options: {
      a: 'Una persona que sirve comida',
      b: 'Una computadora que proporciona servicios a otras computadoras',
      c: 'Un tipo de archivo',
      d: 'Un programa de diseño',
    },
    correctAnswer: 'b',
    explanation: 'Un servidor es una computadora que proporciona servicios (como almacenamiento, procesamiento) a otras computadoras.',
  },
  {
    id: 'b4_q19',
    block: 'block4',
    theme: 8,
    text: '¿Qué es un cliente?',
    options: {
      a: 'Una persona que compra',
      b: 'Una computadora que solicita servicios a un servidor',
      c: 'Un tipo de archivo',
      d: 'Un programa de diseño',
    },
    correctAnswer: 'b',
    explanation: 'Un cliente es una computadora que solicita servicios a un servidor.',
  },
  {
    id: 'b4_q20',
    block: 'block4',
    theme: 9,
    text: '¿Qué es el ancho de banda?',
    options: {
      a: 'El tamaño de un archivo',
      b: 'La cantidad máxima de datos que se pueden transmitir en una red',
      c: 'Un tipo de virus',
      d: 'Un programa de diseño',
    },
    correctAnswer: 'b',
    explanation: 'El ancho de banda es la cantidad máxima de datos que se pueden transmitir en una red en un período de tiempo.',
  },

  // ============ PREGUNTAS GENERALES (20 preguntas) ============
  {
    id: 'general_q1',
    block: 'block1',
    theme: 1,
    text: '¿En qué año se aprobó la Constitución Española actual?',
    options: {
      a: '1975',
      b: '1978',
      c: '1982',
      d: '1985',
    },
    correctAnswer: 'b',
    explanation: 'La Constitución Española fue aprobada en 1978.',
  },
  {
    id: 'general_q2',
    block: 'block2',
    theme: 1,
    text: '¿Cuántos bytes hay en 1 megabyte?',
    options: {
      a: '1,000',
      b: '100,000',
      c: '1,000,000',
      d: '10,000,000',
    },
    correctAnswer: 'c',
    explanation: '1 megabyte (MB) equivale a 1,000,000 bytes.',
  },
  {
    id: 'general_q3',
    block: 'block3',
    theme: 2,
    text: '¿Cuál es el paradigma de programación más utilizado actualmente?',
    options: {
      a: 'Programación funcional',
      b: 'Programación orientada a objetos',
      c: 'Programación declarativa',
      d: 'Programación imperativa',
    },
    correctAnswer: 'b',
    explanation: 'La programación orientada a objetos es el paradigma más utilizado en la actualidad.',
  },
  {
    id: 'general_q4',
    block: 'block4',
    theme: 2,
    text: '¿Cuál es el puerto estándar para HTTP?',
    options: {
      a: '21',
      b: '25',
      c: '80',
      d: '443',
    },
    correctAnswer: 'c',
    explanation: 'El puerto estándar para HTTP es el puerto 80.',
  },
  {
    id: 'general_q5',
    block: 'block1',
    theme: 7,
    text: '¿Cuál es el principal objetivo del RGPD?',
    options: {
      a: 'Aumentar la recopilación de datos',
      b: 'Proteger los derechos de las personas respecto a datos',
      c: 'Facilitar el comercio de datos',
      d: 'Eliminar todas las bases de datos',
    },
    correctAnswer: 'b',
    explanation: 'El RGPD protege los derechos y libertades de las personas respecto al tratamiento de datos personales.',
  },
  {
    id: 'general_q6',
    block: 'block2',
    theme: 4,
    text: '¿Cuál es el sistema operativo más utilizado en computadoras personales?',
    options: {
      a: 'Linux',
      b: 'macOS',
      c: 'Windows',
      d: 'Unix',
    },
    correctAnswer: 'c',
    explanation: 'Windows es el sistema operativo más utilizado en computadoras personales.',
  },
  {
    id: 'general_q7',
    block: 'block3',
    theme: 3,
    text: '¿Cuál es la sentencia SQL para eliminar datos?',
    options: {
      a: 'INSERT',
      b: 'UPDATE',
      c: 'DELETE',
      d: 'SELECT',
    },
    correctAnswer: 'c',
    explanation: 'DELETE es la sentencia SQL utilizada para eliminar datos de una base de datos.',
  },
  {
    id: 'general_q8',
    block: 'block4',
    theme: 1,
    text: '¿Cuál es el modelo de referencia más utilizado en redes?',
    options: {
      a: 'Modelo de 3 capas',
      b: 'Modelo OSI',
      c: 'Modelo de 5 capas',
      d: 'Modelo de 2 capas',
    },
    correctAnswer: 'b',
    explanation: 'El modelo OSI (Open Systems Interconnection) es el modelo de referencia más utilizado en redes.',
  },
  {
    id: 'general_q9',
    block: 'block1',
    theme: 8,
    text: '¿Qué es la administración electrónica?',
    options: {
      a: 'Solo enviar correos electrónicos',
      b: 'Prestar servicios públicos mediante medios electrónicos',
      c: 'Un programa de contabilidad',
      d: 'Un tipo de virus',
    },
    correctAnswer: 'b',
    explanation: 'La administración electrónica es la prestación de servicios públicos mediante medios electrónicos.',
  },
  {
    id: 'general_q10',
    block: 'block2',
    theme: 5,
    text: '¿Cuál es la principal ventaja de las bases de datos relacionales?',
    options: {
      a: 'Son muy lentas',
      b: 'Permiten organizar datos de forma estructurada y eficiente',
      c: 'No permiten consultas complejas',
      d: 'Ocupan mucho espacio',
    },
    correctAnswer: 'b',
    explanation: 'Las bases de datos relacionales permiten organizar datos de forma estructurada y realizar consultas eficientes.',
  },
  {
    id: 'general_q11',
    block: 'block3',
    theme: 4,
    text: '¿Qué es la encapsulación en POO?',
    options: {
      a: 'Envolver datos en paquetes',
      b: 'Ocultar detalles internos de un objeto',
      c: 'Crear múltiples copias de un objeto',
      d: 'Eliminar datos innecesarios',
    },
    correctAnswer: 'b',
    explanation: 'La encapsulación es el mecanismo de ocultar los detalles internos de un objeto.',
  },
  {
    id: 'general_q12',
    block: 'block4',
    theme: 5,
    text: '¿Qué es un certificado SSL?',
    options: {
      a: 'Un documento de identidad',
      b: 'Un certificado digital para cifrar comunicaciones web',
      c: 'Un tipo de archivo',
      d: 'Un programa antivirus',
    },
    correctAnswer: 'b',
    explanation: 'Un certificado SSL es un certificado digital que cifra la comunicación entre cliente y servidor web.',
  },
  {
    id: 'general_q13',
    block: 'block1',
    theme: 4,
    text: '¿Cuál es el derecho fundamental más importante?',
    options: {
      a: 'Derecho al trabajo',
      b: 'Derecho a la vida',
      c: 'Derecho a la educación',
      d: 'Derecho a la vivienda',
    },
    correctAnswer: 'b',
    explanation: 'El derecho a la vida es considerado el derecho fundamental más importante.',
  },
  {
    id: 'general_q14',
    block: 'block2',
    theme: 2,
    text: '¿Cuál es la velocidad típica de un puerto HDMI?',
    options: {
      a: '1 Gbps',
      b: '10 Gbps',
      c: '48 Gbps',
      d: '100 Gbps',
    },
    correctAnswer: 'c',
    explanation: 'HDMI 2.1 tiene una velocidad de hasta 48 Gbps.',
  },
  {
    id: 'general_q15',
    block: 'block3',
    theme: 6,
    text: '¿Qué es JavaScript?',
    options: {
      a: 'Un lenguaje de programación para servidores',
      b: 'Un lenguaje de programación para navegadores web',
      c: 'Un sistema operativo',
      d: 'Un tipo de archivo',
    },
    correctAnswer: 'b',
    explanation: 'JavaScript es un lenguaje de programación que se ejecuta en navegadores web para crear interactividad.',
  },
  {
    id: 'general_q16',
    block: 'block4',
    theme: 7,
    text: '¿Cuál es el puerto estándar para HTTPS?',
    options: {
      a: '80',
      b: '110',
      c: '443',
      d: '25',
    },
    correctAnswer: 'c',
    explanation: 'El puerto estándar para HTTPS es el puerto 443.',
  },
  {
    id: 'general_q17',
    block: 'block1',
    theme: 6,
    text: '¿Qué es la firma electrónica?',
    options: {
      a: 'Una imagen de una firma escrita',
      b: 'Un mecanismo para autenticar documentos electrónicos',
      c: 'Un tipo de archivo',
      d: 'Un programa de diseño',
    },
    correctAnswer: 'b',
    explanation: 'La firma electrónica es un mecanismo criptográfico para autenticar documentos electrónicos.',
  },
  {
    id: 'general_q18',
    block: 'block2',
    theme: 3,
    text: '¿Cuántos valores puede representar un byte?',
    options: {
      a: '256',
      b: '128',
      c: '512',
      d: '1024',
    },
    correctAnswer: 'a',
    explanation: 'Un byte puede representar 256 valores diferentes (0-255).',
  },
  {
    id: 'general_q19',
    block: 'block3',
    theme: 1,
    text: '¿Qué es la normalización en bases de datos?',
    options: {
      a: 'Hacer que todos los datos sean iguales',
      b: 'Un proceso para organizar datos y eliminar redundancias',
      c: 'Eliminar datos innecesarios',
      d: 'Crear copias de seguridad',
    },
    correctAnswer: 'b',
    explanation: 'La normalización es un proceso para organizar datos en una base de datos y eliminar redundancias.',
  },
  {
    id: 'general_q20',
    block: 'block4',
    theme: 3,
    text: '¿Cuál es el rango de direcciones IP privadas de Clase A?',
    options: {
      a: '10.0.0.0 a 10.255.255.255',
      b: '172.16.0.0 a 172.31.255.255',
      c: '192.168.0.0 a 192.168.255.255',
      d: '127.0.0.0 a 127.255.255.255',
    },
    correctAnswer: 'a',
    explanation: 'El rango de direcciones IP privadas de Clase A es 10.0.0.0 a 10.255.255.255.',
  },
];
